-- WY Wallet Mobile: multi-user schema isolated from the existing Streamlit tables.
-- Safe to run in the same Supabase project: it creates only wallet_* objects.

create extension if not exists pgcrypto;

create table if not exists public.wallet_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  email text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.wallet_categories (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null check (length(trim(name)) between 1 and 60),
  created_at timestamptz not null default now(),
  unique (user_id, name)
);

create table if not exists public.wallet_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  date date not null default current_date,
  item text not null check (length(trim(item)) between 1 and 180),
  category text not null default '其他',
  type text not null default 'Expense' check (type in ('Expense', 'Income')),
  amount numeric(14,2) not null check (amount > 0),
  note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists wallet_transactions_user_date_idx
  on public.wallet_transactions(user_id, date desc, created_at desc);
create index if not exists wallet_transactions_user_category_idx
  on public.wallet_transactions(user_id, category);

alter table public.wallet_profiles enable row level security;
alter table public.wallet_categories enable row level security;
alter table public.wallet_transactions enable row level security;

drop policy if exists "wallet_profiles_select_own" on public.wallet_profiles;
drop policy if exists "wallet_profiles_update_own" on public.wallet_profiles;
drop policy if exists "wallet_categories_select_own" on public.wallet_categories;
drop policy if exists "wallet_categories_insert_own" on public.wallet_categories;
drop policy if exists "wallet_categories_update_own" on public.wallet_categories;
drop policy if exists "wallet_categories_delete_own" on public.wallet_categories;
drop policy if exists "wallet_transactions_select_own" on public.wallet_transactions;
drop policy if exists "wallet_transactions_insert_own" on public.wallet_transactions;
drop policy if exists "wallet_transactions_update_own" on public.wallet_transactions;
drop policy if exists "wallet_transactions_delete_own" on public.wallet_transactions;

create policy "wallet_profiles_select_own"
  on public.wallet_profiles for select
  using ((select auth.uid()) = user_id);
create policy "wallet_profiles_update_own"
  on public.wallet_profiles for update
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "wallet_categories_select_own"
  on public.wallet_categories for select
  using ((select auth.uid()) = user_id);
create policy "wallet_categories_insert_own"
  on public.wallet_categories for insert
  with check ((select auth.uid()) = user_id);
create policy "wallet_categories_update_own"
  on public.wallet_categories for update
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy "wallet_categories_delete_own"
  on public.wallet_categories for delete
  using ((select auth.uid()) = user_id);

create policy "wallet_transactions_select_own"
  on public.wallet_transactions for select
  using ((select auth.uid()) = user_id);
create policy "wallet_transactions_insert_own"
  on public.wallet_transactions for insert
  with check ((select auth.uid()) = user_id);
create policy "wallet_transactions_update_own"
  on public.wallet_transactions for update
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy "wallet_transactions_delete_own"
  on public.wallet_transactions for delete
  using ((select auth.uid()) = user_id);

create or replace function public.wallet_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists wallet_profiles_touch_updated_at on public.wallet_profiles;
create trigger wallet_profiles_touch_updated_at
before update on public.wallet_profiles
for each row execute function public.wallet_touch_updated_at();

drop trigger if exists wallet_transactions_touch_updated_at on public.wallet_transactions;
create trigger wallet_transactions_touch_updated_at
before update on public.wallet_transactions
for each row execute function public.wallet_touch_updated_at();

create or replace function public.wallet_seed_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.wallet_profiles(user_id, display_name, email, avatar_url)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', split_part(coalesce(new.email, ''), '@', 1)),
    new.email,
    new.raw_user_meta_data->>'avatar_url'
  )
  on conflict (user_id) do update set
    display_name = excluded.display_name,
    email = excluded.email,
    avatar_url = excluded.avatar_url;

  insert into public.wallet_categories(user_id, name)
  select new.id, category
  from unnest(array['饮食','交通','购物','居住','娱乐','医疗','教育','投资','旅游','其他']) as category
  on conflict (user_id, name) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created_wallet on auth.users;
create trigger on_auth_user_created_wallet
after insert on auth.users
for each row execute function public.wallet_seed_user();

insert into public.wallet_profiles(user_id, display_name, email, avatar_url)
select
  id,
  coalesce(raw_user_meta_data->>'full_name', raw_user_meta_data->>'name', split_part(coalesce(email, ''), '@', 1)),
  email,
  raw_user_meta_data->>'avatar_url'
from auth.users
on conflict (user_id) do nothing;

insert into public.wallet_categories(user_id, name)
select u.id, c.category
from auth.users u
cross join unnest(array['饮食','交通','购物','居住','娱乐','医疗','教育','投资','旅游','其他']) as c(category)
on conflict (user_id, name) do nothing;
